save_dir: ckpt/demo
best_model_path: ckpt/demo/best_model
last_model_path: ckpt/demo/last_model
pretrained_model_path: ./enpar
train_model_dir: ckpt/demo/batch

vocabulary_file: ckpt/demo/vocabulary.pickle
train_file: data/demo/train.json
dev_file: data/demo/dev.json
test_file: data/demo/test.json
max_sent_len: 200
max_wordpiece_len: 512
entity_schema: BIEOU
low_case: 0

embedding_dims: 100
word_dims: 100
char_dims: 50
char_batch_size: 128
char_kernel_sizes: [2, 3, 4]
char_output_channels: 25
embedding_model: bert
entity_model: pipeline
lstm_layers: 0
lstm_hidden_unit_dims: 512
schedule_k: 3.0
entity_cnn_kernel_sizes: [2, 3, 4]
entity_cnn_output_channels: 100
context_cnn_kernel_sizes: [3, 4, 5]
context_cnn_output_channels: 100
ent_output_size: 192
context_output_size: 128
ent_mention_output_size: 256
span_batch_size: 128
dropout: 0.1
bert_model_name: bert-base-cased
bert_output_size: 0
bert_dropout: 0.1

gradient_clipping: 1.0
learning_rate: 25e-6
lr_decay_rate: 0.90
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1e-6
adam_weight_decay_rate: 0.01

seed: 5216
epochs: 200
pretrain_epochs: 5
warmup_rate: 0.2
early_stop: 100
train_batch_size: 32
test_batch_size: 32
gradient_accumulation_steps: 1
logging_steps: 32
validate_every: 15000
device: -1
root_log_level: DEBUG
log_file: ckpt/demo/train.log
console_log_level: NOTSET
file_log_level: NOTSET
